graphhopper:
  graph.flag_encoders: car|turn_costs=true

  graph.elevation.provider: multi
  graph.elevation.cache_dir: /Users/develar/elevation

  prepare.ch.weightings: no

  # The hybrid mode can be enabled with
  prepare.lm.weightings: fastest
  prepare.lm.threads: 2

  # avoid being stuck in a (oneway) subnetwork, see https://discuss.graphhopper.com/t/93
  prepare.min_network_size: 200
  prepare.min_one_way_network_size: 200

  # You can limit the max distance between two consecutive waypoints of flexible routing requests to be less or equal
  # the given distance in meter. Default is set to 1000km.
  routing.non_ch.max_waypoint_distance: 1000000

  graph.dataaccess: RAM_STORE