site_name: Routing data for GraphHopper
use_directory_urls: false
theme:
  name: material
  favicon: favicon.ico
  logo:
    icon: 'directions'
  palette:
    primary: 'light blue'
    accent: 'light blue'
nav:
  - 'Hike and Bike': 'index.md'
  - 'GraphHopper vs BRouter': 'gh-brouter.md'

repo_name: 'develar/gh-routing-data'
repo_url: 'https://github.com/develar/gh-routing-data'
edit_uri: ""
strict: true

markdown_extensions:
  - admonition
  - smarty
  - pymdownx.smartsymbols
  - pymdownx.details
  - toc:
      permalink: true

plugins: []

google_analytics:
  - 'UA-120844885-1'
  - 'graphhopper.develar.org'