version: "3.6"
# minio doesn't allow short names like gh, so, we use gh-data
# minio exposes all sub directories as buckets, so, we cannot use www to store gh data directly
services:
  minio:
    image: minio/minio
    command: server /data
    secrets:
      - access_key
      - secret_key
    ports:
      - target: 9000
        published: 9000
        mode: host
    volumes:
      - type: volume
        source: gh-data
        target: /data
        volume:
          nocopy: true
    healthcheck:
      disable: true
    logging:
      driver: json-file
      options:
        max-size: "64m"
        max-file: "10"
    deploy:
     restart_policy:
      delay: 10s
      max_attempts: 4
      window: 60s

configs:
  nginx:
    file: ./nginx.conf

secrets:
  access_key:
    external: true
  secret_key:
    external: true

volumes:
  gh-data: