version: "3.6"
# minio doesn't allow short names like gh, so, we use gh-data
# minio exposes all sub directories as buckets, so, we cannot use www to store gh data directly
# minio doesn't support several disk devices, but Scaleway provides 100 GB SSD as 2 volumes, not one, so, 2 minio servers started to upload data
services:
  minio-eu:
    image: minio/minio
    command: server /data
    secrets: &MINIO_SECRETS
      - access_key
      - secret_key
    ports:
      - target: 9000
        published: 9000
        mode: host
    volumes:
      - type: volume
        source: gh-data-eu
        target: /data
        volume:
          nocopy: true
    healthcheck:
      disable: true
    logging: &LOGGING
      driver: json-file
      options:
        max-size: "64m"
        max-file: "10"
    deploy: &MINIO_DEPLOY
      restart_policy:
        delay: 10s
        max_attempts: 4
        window: 60s
  minio-other:
    image: minio/minio
    command: server /data
    secrets: *MINIO_SECRETS
    ports:
      - target: 9000
        published: 9001
        mode: host
    volumes:
      - type: volume
        source: gh-data-other
        target: /data
        volume:
          nocopy: true
    healthcheck:
      disable: true
    logging: *LOGGING
    deploy: *MINIO_DEPLOY
  caddy:
    image: abiosoft/caddy
    configs:
      - source: caddy
        target: /etc/Caddyfile
    volumes:
      - /etc/caddycerts:/etc/caddycerts
      - type: volume
        source: gh-data-eu
        target: /srv/gh-data-eu
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: gh-data-other
        target: /srv/gh-data-other
        read_only: true
        volume:
          nocopy: true
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    environment:
      - ACME_AGREE=true
      - CADDYPATH=/etc/caddycerts

configs:
  caddy:
    file: ./Caddyfile

secrets:
  access_key:
    external: true
  secret_key:
    external: true

volumes:
  gh-data-eu:
    driver: local
    driver_opts:
      type: ext4
      device: /dev/vdb
  gh-data-other: