# ansible-playbook -v -i configs/server/production.yml configs/server/site.yml
- hosts: all
  gather_facts: False
  vars:
    deploy_config_dir: /tmp/gh-data-server
  tasks:
  # ensure that no stale files
  - name: Clear deploy config dir
    file:
      path: "{{ deploy_config_dir }}"
      state: absent
  - name: Create deploy config dir
    file:
      path: "{{ deploy_config_dir }}"
      state: directory

  - name: Copy docker-compose.yml
    copy:
      src: docker-compose.yml
      dest: "{{ deploy_config_dir }}/docker-compose.yml"
  - name: Copy nginx.conf
    copy:
      src: nginx.conf
      dest: "{{ deploy_config_dir }}/nginx.conf"

  - name: Deploy stack
    command: docker stack deploy --prune --compose-file={{ deploy_config_dir }}/docker-compose.yml site