# ansible-playbook -v -i configs/server/production.yml configs/server/site.yml
# on first run don't forget to 1) create gh-bucket using web interface (host:9000) 2) set bucket policy for / to "Read Only""
- hosts: all
  gather_facts: False
  vars:
    deploy_config_dir: /tmp/gh-data-server
  tasks:
  # ensure that no stale files
  - name: Clear deploy config dir
    file:
      path: "{{ deploy_config_dir }}"
      state: absent
  - name: Create deploy config dir
    file:
      path: "{{ deploy_config_dir }}"
      state: directory

  - name: Copy files
    copy:
      src: "{{ item.name }}"
      dest: "{{ deploy_config_dir }}/{{ item.name }}"
    with_items:
      - { name: docker-compose.yml }

  - name: Deploy stack
    command: docker stack deploy --prune --compose-file={{ deploy_config_dir }}/docker-compose.yml site